### ISSUE TITLE
Cron commands not executed in docker container

### ISSUE THREAD

**Issue by ciesla05** [pavlovdo/pystormon#8]
I used today this project and its working well but I have problem with docker. In running container cron commands are not not executed, but when I go to container and manualy execute scripts then its working. So I think its something with cron.

**Comment by pavlovdo** [comment]
Hi!
I removed absolute path to crond from CMD in container.
Try build container now.

**Comment by ciesla05** [comment]
Not helped but when in container I add execution rights then its start working.
example: 
chmod +x /etc/zabbix/externalscripts/pystormon/storage_perfomance.py

**Comment by pavlovdo** [comment]
Hi!
Your issue is probably due to umask other than 0002. As result, after clone from github, your python scripts haven't permissions to execute for user root. You can check it via command umask.
For fix this issue, add permission to execute for python scripts in project directory, remove container and rebuild it.

**Comment by pavlovdo** [comment]
The cause of the issue was umask probably.
